### ISSUE TITLE
Add second in screensaver

### ISSUE THREAD

**Issue by Th0m4** [mattiarossini/MinimalClock#2]
Hi ! 
Love the screensaver but can you add an option to have the seconds print on the screen.

**Comment by mattiarossini** [comment]
Hi, thank you!

Check this fork if you want to display the seconds: [https://github.com/thomasjpr/MinimalClock](https://github.com/thomasjpr/MinimalClock)

**Comment by Th0m4** [comment]
Thanks !😃
