### ISSUE TITLE
Support Catalina

### ISSUE THREAD

**Issue by sebastianludwig** [mattiarossini/MinimalClock#3]
Hey, I really like the aesthetics and would love to use your screensaver. However I'm not on Big Sur yet. I saw that the deployment target only [changed recently](https://github.com/mattiarossini/MinimalClock/commit/35082492789007feb9fdf0b3afabde2a36f1fb47#diff-6e6c1dc52628dc5e2e4bd2ec0551f404278fb8db2fe37476e4ff7e1e8e18d237L247). Was there a specific need for that or would it be possible to also support "older" versions of macOS easily?

I'd also be happy to use an old release, but it seems that 1.0 from 2018 got replaced with a new build?

**Comment by mattiarossini** [comment]
Hi, thank you very much!

You can try to install my last release.
If it doesn't work, you can download the old release here: [MinimalClock.saver.zip](https://github.com/mattiarossini/MinimalClock/files/5639983/MinimalClock.saver.zip)

**Comment by sebastianludwig** [comment]
Computer says "no". Tried both versions, same result

<img width="427" alt="Screen Shot 2020-12-04 at 17 24 55" src="https://user-images.githubusercontent.com/1715010/101188177-a26b6780-3655-11eb-9c25-191084a02f7e.png">

**Comment by mattiarossini** [comment]
Here I set the version to macOS 10.15.
[MinimalClock.saver.zip](https://github.com/mattiarossini/MinimalClock/files/5645334/MinimalClock.saver.zip)

**Comment by sebastianludwig** [comment]
Awesome, that works - thank you very much 👍

**Comment by mattiarossini** [comment]
Great!
