### ISSUE TITLE
Installation for macos Catalina 10.15.7

### ISSUE THREAD

**Issue by ffontcl** [mattiarossini/MinimalClock#4]
It would be great if the screensaver was compatible with macos Catalina 10.15.7!

**Comment by mattiarossini** [comment]
Try using this .zip: [https://github.com/mattiarossini/MinimalClock/issues/3#issuecomment-739009611 ](https://github.com/mattiarossini/MinimalClock/issues/3#issuecomment-739009611)

**Comment by ffontcl** [comment]
Thanks!
